
<rules xmlns="http://drools.org/rules">

  <semantics module="org.drools.semantics.java"/>

  <rule-set name="Fishmonger Rules"
           xmlns:java="http://drools.org/semantics/java">

    <rule name="Explode Cart">

      <parameter identifier="cart">
        <java:class type="fishmonger.ShoppingCart"/>
      </parameter>
      <consequence>
        <java:consequence>
         
          import java.util.Iterator;

          System.err.println( "Examining each item in the shopping cart." );

          Iterator itemIter = cart.getItems().iterator();

          while ( itemIter.hasNext() )
          {
              assertObject( itemIter.next() );
          }

        </java:consequence>
      </consequence>

    </rule>

    <rule name="Free Fish Food Special">

      <parameter identifier="cart">
        <java:class type="fishmonger.ShoppingCart"/>
      </parameter>
      <parameter identifier="item">
        <java:class type="fishmonger.CartItem"/>
      </parameter>

      <condition>
        <java:condition>item.getName().equals( "tropical fish" )</java:condition>
      </condition>

      <condition>
        <java:condition>cart.getItems( "tropical fish food" ).size() == 0</java:condition>
      </condition>

      <consequence>
        <java:consequence>
          System.err.println( "Adding free tropical fish food sample to cart" );

          cart.addItem( new fishmonger.CartItem( "tropical fish food sample", 0.00 ) );
        </java:consequence>
      </consequence>

    </rule>

  </rule-set>

</rules>

