<rule-set 
    name="JavaRules.org Test Agent Drools Port"
    xmlns="http://drools.org/rules"
    xmlns:java="http://drools.org/semantics/java"
    description="Some rules for the JavaOne demo">

<!-- Rules -->
  <rule name="Say hello if Mozilla User">
    <parameter identifier="s">
      <java:class>java.lang.String</java:class>
    </parameter>
    <java:condition> s.startsWith("Gecko") </java:condition>
    <java:consequence> assertObject("Hello Mozilla user!"); </java:consequence>
  </rule>
    
  <rule name="Say hello if IE user">
    <parameter identifier="s">
        <java:class>java.lang.String</java:class>
    </parameter>
    <java:condition> s.startsWith("MSIE") </java:condition>
    <java:consequence> assertObject("Hello IE user!"); </java:consequence>
  </rule>

</rule-set>