
<rule-set name="Sisters Rules"
         xmlns="http://drools.org/rules"
         xmlns:java="http://drools.org/semantics/java">

  <rule name="Find Sisters" salience="10">

    <parameter identifier="person">
      <java:class type="sisters.Person"/>
    </parameter>

    <parameter identifier="sister">
      <java:class type="sisters.Person"/>
    </parameter>

    <java:condition>
        person.hasSister( sister )
    </java:condition>

    <java:consequence>
        assertObject(  person + ": I like cheese" );
        assertObject(  "bob says: " +  person + " and " + sister + " are sisters" );
    </java:consequence>

  </rule>

  <rule name="Message Received" salience="0">
    <parameter identifier="message">
      <java:class type="java.lang.String"/>
    </parameter>

    <java:condition>
        message.startsWith( "bob says:" );
    </java:condition>

    <java:consequence>
        System.err.println( "Message from bob received." );
        System.err.println( message );
    </java:consequence>

  </rule>

</rule-set>
