
<rule-set name="test rules"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">

    <rule name="test:1">
        <parameter identifier="string">
            <java:class type="java.lang.String"/>
        </parameter>

        <parameter identifier="props">
            <java:class type="java.util.Properties"/>
        </parameter>

        <java:condition>props.getProperty( "test" ) != null</java:condition>

        <java:consequence>
            props.setProperty( "test", "success" );
        </java:consequence>
    </rule>
</rule-set>
