<rule-set name="Inactive User" 
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">

    <rule name="Invalid Participant">
         <parameter identifier="participantList">
            <java:class type="java.util.ArrayList"/>
         </parameter>

         <parameter identifier="pt">
            <java:class type="org.drools.misc.Participant"/>
         </parameter>

         <java:condition> pt.isActive() </java:condition>

          <java:consequence>
              System.out.println("remove: " + pt);
              participantList.remove(pt);
          </java:consequence>
      </rule>
</rule-set>
