<?xml version="1.0" ?> 
<rule-set name="Engine2" 
	xmlns="http://drools.org/rules" 
	xmlns:java="http://drools.org/semantics/java" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
	xs:schemaLocation="http://drools.org/rules rules.xsd http://drools.org/semantics/java java.xsd">
	
	<java:import>java.lang.Object</java:import> 
	<rule name="Debug">
		<parameter identifier="object">
			<class>Object</class> 
		</parameter>
		<java:consequence>
			System.out.println("Engine 2 Asserted object: " + object);
		</java:consequence> 
	</rule>
</rule-set>