<?xml version="1.0"?>

<rule-set name="HelloWorld" xmlns="http://drools.org/rules"
    xmlns:annotation="http://drools.org/semantics/annotation"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/annotation annotation.xsd">

    <annotation:rule name="Hello World"
        class="org.drools.semantics.annotation.examples.helloworld.HelloWorldRules$Hello" />

    <annotation:rule name="Goodbye Cruel World"
        class="org.drools.semantics.annotation.examples.helloworld.HelloWorldRules$Goodbye" />

    <annotation:rule name="Debug"
        class="org.drools.semantics.annotation.examples.helloworld.HelloWorldRules$Debug" />

</rule-set>
