<?xml version="1.0"?>

<rule-set name="conway"
    xmlns="http://drools.org/rules"
    xmlns:annotation="http://drools.org/semantics/annotation"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
                       http://drools.org/semantics/annotation annotation.xsd">

    <annotation:rule name="Give Birth"
        class="com.ociweb.conway.rules.GiveBirth"/>

    <annotation:rule name="Kill The Overcrowded"
        class="com.ociweb.conway.rules.KillTheOvercrowded"/>

    <annotation:rule name="Kill The Lonely"
        class="com.ociweb.conway.rules.KillTheLonely"/>

</rule-set>