<?xml version="1.0" encoding="UTF-8"?>

<rule-set name="Sisters Rules"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="Find Sisters">

        <parameter identifier="person">
          <class> org.drools.jsr94.rules.Person </class>
        </parameter>

        <parameter identifier="sister">
          <class> org.drools.jsr94.rules.Person </class>
        </parameter>

        <!--<java:condition> person.getName().compareTo( sister.getName() ) &gt; 0</java:condition>-->
        <java:condition> person.hasSister( sister ) </java:condition>

        <java:consequence>
            drools.assertObject( person + " and " + sister + " are sisters" );
        </java:consequence>
    </rule>

</rule-set>
