
<rules xmlns="http://drools.org/rules">

  <semantics module="org.drools.semantics.java"/>
  <semantics module="org.drools.semantics.jelly"/>

  <rule-set name="Sisters Rules"
           xmlns:java="http://drools.org/semantics/java"
           xmlns:jelly="http://drools.org/semantics/jelly">

    <rule name="Find Sisters" salience="10">

      <parameter identifier="person">
        <java:class type="sisters.Person"/>
      </parameter>

      <parameter identifier="sister">
        <java:class type="sisters.Person"/>
      </parameter>

      <condition>
        <java:condition>person.hasSister( sister )</java:condition>
      </condition>

      <consequence>

        <java:consequence>
         
          assertObject(  person + ": I like cheese" );
          assertObject(  "bob says: " +  person + " and " + sister + " are sisters" );

        </java:consequence>

      </consequence>

    </rule>

    <rule name="Message Received" salience="20">
      <parameter identifier="message">
        <java:class type="java.lang.String"/>
      </parameter>

      <condition>
        <java:condition>
          message.startsWith( "bob says:" );
        </java:condition>
      </condition>

      <consequence>
        <java:consequence>
            System.err.println( "Getting message from appData." );
            System.err.println( appData.get("message") );
            System.err.println();
            System.err.println( "Message from bob received." );
            System.err.println( message );
        </java:consequence>
      </consequence>

    </rule>

  </rule-set>

</rules>

