<?xml version="1.0"?>

<rule-set name="HelloWorld" xmlns="http://drools.org/rules"
    xmlns:java="http://drools.org/semantics/java"
    xmlns:python="http://drools.org/semantics/python"
    xmlns:annotation="http://drools.org/semantics/annotation"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd
                             http://drools.org/semantics/python python.xsd
                             http://drools.org/semantics/annotation annotation.xsd
                             ">

    <java:import>java.lang.Object</java:import>
    <java:import>java.lang.String</java:import>

    <java:functions>
        public void printHelloWorld(String hello) {
        System.err.println(hello + " World"); }
    </java:functions>

    <rule name="Hello World">
        <parameter identifier="hello">
            <class>String</class>
        </parameter>

        <java:condition>
            hello.equals("Hello")
        </java:condition>

        <java:consequence>
            printHelloWorld(hello);
        </java:consequence>
    </rule>

    <annotation:rule name="Goodbye Cruel World"
        class="org.drools.semantics.annotation.examples.helloworld.HelloWorldRules$Goodbye" />

    <rule name="Debug">
        <parameter identifier="object">
            <class>Object</class>
        </parameter>

        <python:consequence>
            print "Asserted object: %s" % object
        </python:consequence>
    </rule>

</rule-set>
