<?xml version="1.0"?>

<rule-set name="HelloWorld"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">

  <rule name="Hello World">
    <parameter identifier="hello">
      <java:class>java.lang.String</java:class>
    </parameter>
    
    <java:condition>hello.equals("Hello")</java:condition>
    
    <java:consequence>
      System.out.println(hello + " World");
    </java:consequence>
  </rule>

  <rule name="Goodbye Cruel World">
    <parameter identifier="goodbye">
      <java:class>java.lang.String</java:class>
    </parameter>
    
    <java:condition>goodbye.equals("Goodbye")</java:condition>
    
    <java:consequence>
      System.out.println(goodbye + " Cruel World");
    </java:consequence>
  </rule>

</rule-set>
