<?xml version="1.0"?>

<rule-set name="HelloWorld"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

  <rule name="Hello World">
    <parameter identifier="hello">
      <class>java.lang.String</class>
    </parameter>

    <declaration identifier="helloString">
      <class>java.lang.String</class>
    </declaration>
    <java:extractor target="helloString">hello.toString()</java:extractor>

    <java:condition>"Hello".equals(helloString)</java:condition>

    <java:consequence>
      System.out.println("parameter: " + hello + " World");
      System.out.println("extractor: " + helloString + " World");
    </java:consequence>
  </rule>

  <rule name="Goodbye Cruel World">
    <parameter identifier="goodbye">
      <class>java.lang.String</class>
    </parameter>

    <declaration identifier="goodbyeString">
      <class>java.lang.String</class>
    </declaration>
    <java:extractor target="goodbyeString">goodbye.toString()</java:extractor>

    <java:condition>"Goodbye".equals(goodbyeString)</java:condition>

    <java:consequence>
      System.out.println("parameter: " + goodbye + " Cruel World");
      System.out.println("extractor: " + goodbyeString + " Cruel World");
    </java:consequence>
  </rule>

</rule-set>
