<?xml version="1.0"?>

<rule-set name="HelloWorld"
          xmlns="http://drools.org/rules"
          xmlns:groovy="http://drools.org/semantics/groovy"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/groovy groovy.xsd">

  <groovy:import>java.lang.Object</groovy:import>
  <groovy:import>java.lang.String</groovy:import>

  <groovy:functions>
  	def helloWorld(String hello)
  	{
  		println hello + " World";
  	}

  	def goodbyeWorld(String goodbye)
  	{
  		println goodbye + " Cruel World";
  	}
  </groovy:functions>

  <rule name="Hello World">
    <parameter identifier="hello">
      <class>String</class>
    </parameter>

    <groovy:condition>hello.equals("Hello")</groovy:condition>

    <groovy:consequence>
      helloWorld(hello);
    </groovy:consequence>
  </rule>

  <rule name="Goodbye Cruel World">
    <parameter identifier="goodbye">
      <class>String</class>
    </parameter>

    <groovy:condition>goodbye.equals("Goodbye")</groovy:condition>

    <groovy:consequence>
      goodbyeWorld(goodbye)
    </groovy:consequence>
  </rule>

  <rule name="Debug">
    <parameter identifier="object">
      <class>Object</class>
    </parameter>

    <groovy:consequence>
      println "Asserted object: " + object ;
    </groovy:consequence>
  </rule>

</rule-set>
