<?xml version="1.0"?>

<rule-set name="State Example"
          xmlns="http://drools.org/rules"
          xmlns:groovy="http://drools.org/semantics/groovy">

   <imports>
     <groovy:import>org.drools.examples.state.State</groovy:import>
   </imports>

    <rule name="Bootstrap">
        <parameter identifier="a">
            <class-field field="name" value="A">State</class-field>
        </parameter>

        <groovy:condition>a.state == "NOTRUN"</groovy:condition>

        <groovy:consequence>
            println "${a.name} finished"
            a.state = "FINISHED"
            drools.modifyObject(a)
        </groovy:consequence>
    </rule>

    <rule name="AtoB" salience="30">
        <parameter identifier="a">
            <class-field field="name" value="A">State</class-field>
       </parameter>
        <parameter identifier="b">
            <class-field field="name" value="B">State</class-field>
        </parameter>

        <groovy:condition>a.state == "FINISHED"</groovy:condition>
        <groovy:condition>b.state == "NOTRUN"</groovy:condition>

        <groovy:consequence>
            println "${b.name} finished"
            b.state = "FINISHED"
            drools.modifyObject(b)
        </groovy:consequence>
    </rule>

    <rule name="BtoC" salience="20">
        <parameter identifier="b">
            <class-field field="name" value="B">State</class-field>
        </parameter>
        <parameter identifier="c">
            <class-field field="name" value="C">State</class-field>
        </parameter>

        <groovy:condition>b.state == "FINISHED"</groovy:condition>
        <groovy:condition>c.state == "NOTRUN"</groovy:condition>

        <groovy:consequence>
            println "${c.name} finished"
            c.state = "FINISHED"
            drools.modifyObject(c)
        </groovy:consequence>
    </rule>



    <rule name="BtoD" salience="10">
        <parameter identifier="b">
            <class-field field="name" value="B">State</class-field>
        </parameter>
        <parameter identifier="d">
            <class-field field="name" value="D">State</class-field>
        </parameter>

        <groovy:condition>b.state == "FINISHED"</groovy:condition>
        <groovy:condition>d.state == "NOTRUN"</groovy:condition>

        <groovy:consequence>
            println "${d.name} finished"
            d.state = "FINISHED"
            drools.modifyObject(d)
        </groovy:consequence>
    </rule>


  </rule-set>
