<rule-set name="Fishmonger Rules" xmlns="http://drools.org/rules" xmlns:java="http://drools.org/semantics/java">

    <rule name="Explode Cart">

      <parameter identifier="cart">
        <java:class>org.drools.examples.fishmonger.ShoppingCart</java:class>
      </parameter>

        <java:consequence>
         
          import java.util.Iterator;

          System.err.println( "Examining each item in the shopping cart." );

          Iterator itemIter = cart.getItems().iterator();

          while ( itemIter.hasNext() )
          {
              assertObject( itemIter.next() );
          }

        </java:consequence>

    </rule>

    <rule name="Free Fish Food Special">

      <parameter identifier="cart">
        <java:class>org.drools.examples.fishmonger.ShoppingCart</java:class>
      </parameter>

      <parameter identifier="item">
        <java:class>org.drools.examples.fishmonger.CartItem</java:class>
      </parameter>

        <java:condition>item.getName().equals( "tropical fish" )</java:condition>

        <java:condition>cart.getItems( "tropical fish food" ).size() == 0</java:condition>

        <java:consequence>
          System.err.println( "Adding free tropical fish food sample to cart" );

          cart.addItem( new org.drools.examples.fishmonger.CartItem( "tropical fish food sample", 0.00 ) );
        </java:consequence>

    </rule>

    <rule name="Suggest Tank">

      <parameter identifier="cart">
        <java:class>org.drools.examples.fishmonger.ShoppingCart</java:class>
      </parameter>

        <java:condition>cart.getItems( "tropical fish" ).size() &gt; 5</java:condition>
        <java:condition>cart.getItems( "tank" ).size() == 0</java:condition>

        <java:consequence>
          System.err.println( "*** SUGGESTION: Would you like to buy a tank for your"
                            + cart.getItems( "tropical fish" ).size() + " fish?" );
        </java:consequence>

    </rule>

    <rule name="Apply Discount">

      <parameter identifier="cart">
        <java:class>org.drools.examples.fishmonger.ShoppingCart</java:class>
      </parameter>

        <java:condition>cart.getGrossCost() &gt; 20.00</java:condition>

        <java:consequence>
          System.err.println( "Applying 15% discount to cart" );
          cart.setDiscount( 0.15 );
        </java:consequence>

    </rule>

  </rule-set>
