
<rules xmlns="http://drools.org/rules">

   <semantics module="org.drools.semantics.java"/>

   <rule-set name="Inactive User" xmlns:java="http://drools.org/semantics/java">
      <rule name="Invalid Participant">

         <parameter identifier="participantList">
            <java:class type="java.util.ArrayList"/>
         </parameter>

         <parameter identifier="pt">
            <java:class type="org.drools.misc.Participant"/>
         </parameter>

         <condition>
            <java:condition> pt.isActive() </java:condition>
         </condition>

         <consequence>
            <java:consequence>
               System.out.println("remove: " + pt);
               participantList.remove(pt);
            </java:consequence>
         </consequence>
      </rule>
   </rule-set>

</rules>

